# Message type for task assignments to robots
# Each field represents the list of tasks assigned to a specific robot.

int32 robot_1_task  # Tasks assigned to Robot 1
int32 robot_2_task  # Tasks assigned to Robot 2
int32 robot_3_task  # Tasks assigned to Robot 3
int32 robot_4_task  # Tasks assigned to Robot 4
int32 robot_5_task
int32 robot_6_task  # Tasks assigned to Robot 1
int32 robot_7_task  # Tasks assigned to Robot 2
int32 robot_8_task  # Tasks assigned to Robot 3
int32 robot_9_task  # Tasks assigned to Robot 4
int32 robot_10_task
int32 robot_11_task  # Tasks assigned to Robot 1
int32 robot_12_task  # Tasks assigned to Robot 2
int32 robot_13_task  # Tasks assigned to Robot 3
int32 robot_14_task  # Tasks assigned to Robot 4
int32 robot_15_task
int32 robot_16_task

# The robot's position in (x, y) format
int32 robot_1_pos
int32 robot_2_pos
int32 robot_3_pos
int32 robot_4_pos
int32 robot_5_pos
int32 robot_6_pos
int32 robot_7_pos
int32 robot_8_pos
int32 robot_9_pos
int32 robot_10_pos
int32 robot_11_pos
int32 robot_12_pos
int32 robot_13_pos
int32 robot_14_pos
int32 robot_15_pos
int32 robot_16_pos