actions:
  load:
    guard: 'b || c  || d || f || g || i || j || k || m || n'
    type: load
    weight: 0
  stay:
    guard: '1'
    synchronized_transition:
      guard: '1'
      type: synchronized_transition
      weight: 0
    type: stay
    weight: 0
  unload:
    guard: ' e || h || l || o '
    type: unload
    weight: 0
state_dim:
- 2d_pose_region
- Drone_state
state_models:
  2d_pose_region:
    initial: '0'
    ts_type: 2d_pose_region
  Drone_state:
    initial: "unloaded"
    nodes:
      loaded:
        attr:
          labels: ['loaded']
        connected_to:
          unloaded: unload
      unloaded:
        attr:
          labels: ['unloaded']
        connected_to:
          loaded: load
    ts_type: Drone_state