actions:
  load:
    guard: '(unloaded) && (bb || bc || bd || be || bh || bi || bj || bk || bl || bm || bn || bo || bp || bq || br || cb || cc || cd || ce || cf || ch || ci || cj || ck || cl || cm || cn || co || cp || cq || cr || db || dc || dd || de || df || dh || di || dj || dk || dl || dm || dn || do || dp || dq || dr || eb || ec || ed || ee || ef || eh || ei || ej || ek || el || em || en || eo || ep || eq || er || fb || fc || fd || fe || ff || fh || fi || fj || fk || fl || fm || fn || fo || fp || fq || fr || gb || gc || gd || ge || gf || gh || gi || gj || gk || gl || gm || gn || go || gp || gq || gr || he || hj || hn || hr)'
    type: load
    weight: 0
  stay:
    guard: '1'
    synchronized_transition:
      guard: '1'
      type: synchronized_transition
      weight: 0
    type: stay
    weight: 0
  unload:
    guard: '(loaded1 || loaded2 || loaded3) && (b || c || d || e) '
    type: unload
    weight: 0
state_dim:
- 2d_pose_region
- Drone_state
state_models:
  2d_pose_region:
    initial: '0'
    ts_type: 2d_pose_region
  Drone_state:
    initial: "unloaded"
    nodes:
      loaded1:
        attr:
          labels: ['loaded1']
        connected_to:
          unloaded: unload
          loaded1: load
          loaded2: load
      loaded2:
        attr:
          labels: ['loaded2']
        connected_to:
          unloaded: unload
          loaded2: load
          loaded3: load
      loaded3:
        attr:
          labels: ['loaded3']
        connected_to:
          unloaded: unload
          loaded3: load
      unloaded:
        attr:
          labels: ['unloaded']
        connected_to:
          loaded1: load
          unloaded: unload
    ts_type: Drone_state
