# 18 tasks
task_points:
  "1,4": 'bb'
  "6,6": 'cb'
  # "1,6.5": 'db'
  # "5.5,9.5": 'eb'
  # "9,6.5": 'fb'

  "1,13.5": 'bc'
  "9,16.5": 'cc'
  # "1,16": 'dc'
  # "6,13": 'ec'

  "11,13.5": 'bd'
  "11,16.5": 'cd'
  "19,16.5": 'dd'
  # "19,19": 'ed'
  # "15,19.5": 'fd'

  "11,4": 'be'
  "19,6.5": 'ce'
  "16,3": 'de'
  # "19,1": 'ee'

# 4 delivery points
delivery_points:
  "6,3": 'b'
  "5,16": 'c'
  "16,13": 'd'
  "16,5.5": 'e'

# task to delivery mapping
task_to_delivery:
  'b': ['bb', 'cb']
  'c': ['bc', 'cc']
  'd': ['bd', 'cd', 'dd']
  'e': ['be', 'ce', 'de']

# special labels
special_labels: ['db', 'eb', 'bb', 'cd', 'fd']


# robot positions
robot_positions:
  "robot1": "1,19"
  "robot2": "11,19"
  "robot3": "9,11"
  "robot4": "11,9"


# special robots
special_robot: ['robot2', 'robot3']