tasks:
  task1:
    hard_task: <>(b) && [](b -> X(loaded && (!c && !d && !e && !f && !h && !i && !j
      && !k && !l && !m ) U (g && unloaded)))
    soft_task: ''
  task2:
    hard_task: <>(c) && [](c -> X(loaded && (!b && !d && !e && !f && !h && !i && !j
      && !k && !l && !m ) U (g && unloaded)))
    soft_task: ''
  task3:
    hard_task: <>(f) && [](f -> X(loaded && (!b && !c && !d && !e && !h && !i && !j
      && !k && !l && !m ) U (g && unloaded)))
    soft_task: ''
  task4:
    hard_task: <>(d) && [](d -> X(loaded && (!b && !c && !f && !g && !h && !i && !j
      && !k && !l && !m ) U (e && unloaded)))
    soft_task: ''
  task5:
    hard_task: <>(h) && [](h -> X(loaded && (!b && !c && !d && !f && !g && !i && !j
      && !k && !l && !m ) U (e && unloaded)))
    soft_task: ''
  task6:
    hard_task: <>(i) && [](i -> X(loaded && (!b && !c && !d && !f && !g && !h && !j
      && !k && !l && !m ) U (e && unloaded)))
    soft_task: ''
  task7:
    hard_task: <>(j) && [](j -> X(loaded && (!b && !c && !d && !f && !g && !h && !i
      && !k && !l && !m ) U (e && unloaded)))
    soft_task: ''
