tasks:
  task1:
    hard_task: <>(b) && [](b -> X(loaded && ((!c) && (!d) && (!f) && (!g) && (!h)
      && (!i) && (!j) && (!k) && (!l) && (!m) && (!n) && (!o) ) U (e && unloaded)))
    soft_task: ''
  task2:
    hard_task: <>(c) && [](c -> X(loaded && ((!b) && (!d) && (!f) && (!g) && (!h)
      && (!i) && (!j) && (!k) && (!l) && (!m) && (!n) && (!o) ) U (e && unloaded)))
    soft_task: ''
  task3:
    hard_task: <>(d) && [](d -> X(loaded && ((!b) && (!c) && (!f) && (!g) && (!h)
      && (!i) && (!j) && (!k) && (!l) && (!m) && (!n) && (!o) ) U (e && unloaded)))
    soft_task: ''
  task4:
    hard_task: <>(f) && [](f -> X(loaded && ((!b) && (!c) && (!d) && (!e) && (!g)
      && (!i) && (!j) && (!k) && (!l) && (!m) && (!n) && (!o) ) U (h && unloaded)))
    soft_task: ''
  task5:
    hard_task: <>(g) && [](g -> X(loaded && ((!b) && (!c) && (!d) && (!e) && (!f)
      && (!i) && (!j) && (!k) && (!l) && (!m) && (!n) && (!o) ) U (h && unloaded)))
    soft_task: ''
  task6:
    hard_task: <>(i) && [](i -> X(loaded && ((!b) && (!c) && (!d) && (!e) && (!f)
      && (!g) && (!h) && (!j) && (!k) && (!m) && (!n) && (!o) ) U (l && unloaded)))
    soft_task: ''
  task7:
    hard_task: <>(j) && [](j -> X(loaded && ((!b) && (!c) && (!d) && (!e) && (!f)
      && (!g) && (!h) && (!i) && (!k) && (!m) && (!n) && (!o) ) U (l && unloaded)))
    soft_task: ''
  task8:
    hard_task: <>(k) && [](k -> X(loaded && ((!b) && (!c) && (!d) && (!e) && (!f)
      && (!g) && (!h) && (!i) && (!j) && (!m) && (!n) && (!o) ) U (l && unloaded)))
    soft_task: ''
  task9:
    hard_task: <>(m) && [](m -> X(loaded && ((!b) && (!c) && (!d) && (!e) && (!f)
      && (!g) && (!h) && (!i) && (!j) && (!k) && (!l) && (!n) ) U (o && unloaded)))
    soft_task: ''
  task10:
    hard_task: <>(n) && [](n -> X(loaded && ((!b) && (!c) && (!d) && (!e) && (!f)
      && (!g) && (!h) && (!i) && (!j) && (!k) && (!l) && (!m) ) U (o && unloaded)))
    soft_task: ''
