# 18 tasks
task_points:
  "2,10": 'bb'
  "8,16": 'cb'


  "10,2": 'bc'
  "16,8": 'cc'





task_to_delivery:
  'b': ['bb', 'cb']
  'c': ['bc', 'cc']



special_labels: []

delivery_points:
  "16,2": 'c'
  "2,16": 'b'


robot_positions:
  "robot1": "2,2"
  "robot2": "16,16"
  # "robot3": "9,11"
  # "robot4": "11,9"


special_robot: []