# 18 tasks
task_points:
  "4,1": 'bb'
  "1,5": 'cb'
  "7,1": 'db'

  "1,7": 'bc'
  "5,7": 'cc'
  "5,11": 'dc'

  "10,11": 'bd'
  "11,7": 'cd'
  "14,7": 'dd'

  "11,5": 'be'
  "14,5": 'ce'
  "14,1": 'de'





task_to_delivery:
  'b': ['bb', 'cb', 'db']
  'c': ['bc', 'cc', 'dc']
  'd': ['bd', 'cd', 'dd']
  'e': ['be', 'ce', 'de']



special_labels: ['bb', 'cb', 'dc']

delivery_points:
  "1,1": 'b'
  "1,11": 'c'
  "13,10": 'd'
  "10,2": 'e'


robot_positions:
  "robot1": "1,9"
  "robot2": "14,11"
  "robot3": "7,5"
  "robot4": "8,5"


special_robot: ['robot1', 'robot3']