task_points:

#11111111111111111111111111111111111111111111
  "1,4": 'bb'
  "6,6": 'cb'
  "1,6.5": 'db'
  "5.5,9.5": 'eb'
  "9,6.5": 'fb'
  "1,1.5": 'gb'

  "1,13.5": 'bc'
  "9,16.5": 'cc'
  "1,16": 'dc'
  "6,13": 'ec'
  "5, 19.5": 'fc'
  "9,19.5": 'gc'

  "11,13.5": 'bd'
  "11,16.5": 'cd'
  "19,16.5": 'dd'
  "19,19": 'ed'
  "15,19.5": 'fd'
  "19, 11": 'gd'

  "11,4": 'be'
  "19,6.5": 'ce'
  "16,3": 'de'
  "19,1": 'ee'
  "11,1.5": 'fe'
  "19,9.5": 'ge'
  "11,6.5": 'he'

#22222222222222222222222222222222222222222222

  "1,24": 'bf'
  "6,26": 'cf'
  "1,26": 'df'
  "5.5,29": 'ef'
  "9,26": 'ff'
  "1,24": 'gf'

  "1,33.5": 'bh'
  "9,36.5": 'ch'
  "1,36": 'dh'
  "6,33": 'eh'
  "5, 39.5": 'fh'
  "9,39.5": 'gh'

  "11,33.5": 'bi'
  "11,36.5": 'ci'
  "19,36.5": 'di'
  "19,39": 'ei'
  "15,39.5": 'fi'
  "19, 31": 'gi'

  "11,24": 'bj'
  "19,26.5": 'cj'
  "16,23": 'dj'
  "19,21": 'ej'
  "11,21": 'fj'
  "19,29.5": 'gj'
  "11,26.5": 'hj'

#33333333333333333333333333333333333333333333
  "21,4": 'bk'
  "26,6": 'ck'
  "21,6.5": 'dk'
  "25.5,9.5": 'ek'
  "29,6.5": 'fk'
  "21,1.5": 'gk'

  "21,13.5": 'bl'
  "29,16.5": 'cl'
  "21,16": 'dl'
  "26,13": 'el'
  "25, 19.5": 'fl'
  "29,19.5": 'gl'

  "31,13.5": 'bm'
  "31,16.5": 'cm'
  "39,16.5": 'dm'
  "39,19": 'em'
  "35,19.5": 'fm'
  "39, 11": 'gm'

  "31,4": 'bn'
  "39,6.5": 'cn'
  "36,3": 'dn'
  "39,1": 'en'
  "31,1.5": 'fn'
  "39,9.5": 'gn'
  "31,6.5": 'hn'

#44444444444444444444444444444444444444444444
  "21,24": 'bo'
  "26,26": 'co'
  "21,26.5": 'do'
  "25.5,29.5": 'eo'
  "29,26.5": 'fo'
  "21,21.5": 'go'

  "21,33.5": 'bp'
  "29,36.5": 'cp'
  "21,36": 'dp'
  "26,33": 'ep'
  "25, 39.5": 'fp'
  "29,39.5": 'gp'

  "31,33.5": 'bq'
  "31,36.5": 'cq'
  "39,36.5": 'dq'
  "39,39": 'eq'
  "35,39.5": 'fq'
  "39, 31": 'gq'

  "31,24": 'br'
  "39,26.5": 'cr'
  "36,23": 'dr'
  "39,21": 'er'
  "31,21": 'fr'
  "39,29.5": 'gr'
  "31,26.5": 'hr'


task_to_delivery:
  'b': ['bb', 'cb', 'db', 'eb', 'fb', 'gb']
  'c': ['bc', 'cc', 'dc', 'ec', 'fc', 'gc']
  'd': ['bd', 'cd', 'dd', 'ed', 'fd', 'gd']
  'e': ['be', 'ce', 'de', 'ee', 'fe', 'ge', 'he']

  'f': ['bf', 'cf', 'df', 'ef', 'ff', 'gf']
  'h': ['bh', 'ch', 'dh', 'eh', 'fh', 'gh']
  'i': ['bi', 'ci', 'di', 'ei', 'fi', 'gi']
  'j': ['bj', 'cj', 'dj', 'ej', 'fj', 'gj', 'hj']

  'k': ['bk', 'ck', 'dk', 'ek', 'fk', 'gk']
  'l': ['bl', 'cl', 'dl', 'el', 'fl', 'gl']
  'm': ['bm', 'cm', 'dm', 'em', 'fm', 'gm']
  'n': ['bn', 'cn', 'dn', 'en', 'fn', 'gn', 'hn']

  'o': ['bo', 'co', 'do', 'eo', 'fo', 'go']
  'p': ['bp', 'cp', 'dp', 'ep', 'fp', 'gp']
  'q': ['bq', 'cq', 'dq', 'eq', 'fq', 'gq']
  'r': ['br', 'cr', 'dr', 'er', 'fr', 'gr', 'hr']

special_labels: ['db', 'eb', 'bb', 'cd', 'fd', 'df', 'ef', 'bf', 'ci', 'fi']

delivery_points:
  "6,3": 'b'
  "5,16": 'c'
  "16,13": 'd'
  "16,5.5": 'e'

  "6,23": 'f'
  "5,36": 'h'
  "16,33": 'i'
  "16,25.5": 'j'

  "26,3": 'k'
  "25,16": 'l'
  "36,13": 'm'
  "36,5.5": 'n'

  "26,23": 'o'
  "25,36": 'p'
  "36,33": 'q'
  "36,25.5": 'r'




robot_positions:
  "robot1": "1,19"
  "robot2": "11,19"
  "robot3": "9,11"
  "robot4": "11,9"

  "robot5": "1,39"
  "robot6": "11,39"
  "robot7": "9,31"
  "robot8": "11,31"

  "robot9": "21,19"
  "robot10": "31,19"
  "robot11": "29,11"
  "robot12": "31,9"

  "robot13": "21,39"
  "robot14": "31,39"
  "robot15": "29,31"
  "robot16": "31,31"