lines:
  - [[0, 6], [6, 6]]
  - [[12, 0], [12, 4]]
  - [[14, 6], [18, 6]]
  - [[6, 14], [6, 18]]
  - [[12, 12], [18, 12]]
  # 边界墙
  - [[0, 0], [18, 0]]      # 下边界
  - [[18, 0], [18, 18]]    # 右边界
  - [[0, 18], [18, 18]]    # 上边界
  - [[0, 0], [0, 18]]      # 左边界